# Site Info
title:              "Manuel Dionne"
blog_title:         "Blog"
projects_title:     "Projects"
description:        "Code, Space and Video Games"
author_name:        "Manuel Dionne" # change this to your name
logo_url:           https://raw.githubusercontent.com/AideTechBot/test-website/master/assets/profile.png # Get it from GitHub API: https://api.github.com/users/<username>

# Site Settings
url:                https://mdionne.me # main url
baseurl:            
permalink:          /:title # Post permalink
timezone:           America/Toronto # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
mathjax:            true  # enables support for mathjax - set to 'false' to disable

# Site Build
highlighter:        rouge
markdown:           kramdown
kramdown:
    input:          GFM
sass:
    style:          :compressed

# Other Params
include:            [ "robots.txt", "resume.html" ]
exclude:            [ "LICENSE", "README.md", "CNAME", "vendor", "Gemfile", "script" ]
plugins:
  - jekyll-sitemap

collections:
  projects:
    output: true

defaults:
  -
    scope:
      path:         ""
    values:
      layout:       "null"
  -
    scope:
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      type:         "posts"
    values:
      layout:       "post"
  -
    scope:
      type: "projects" 
    values:
      layout: "page"
